definitions:
  hydration.CreateEntryRequest:
    properties:
      amount:
        minimum: 1
        type: integer
      type:
        type: string
    required:
    - amount
    - type
    type: object
  hydration.HydrationEntry:
    properties:
      amount:
        type: integer
      id:
        type: string
      timestamp:
        type: string
      type:
        type: string
      user_id:
        type: string
    type: object
  hydration.HydrationStats:
    properties:
      goal:
        type: integer
      goal_percentage:
        type: integer
      total_month:
        type: integer
      total_today:
        type: integer
      total_week:
        type: integer
    type: object
info:
  contact: {}
paths:
  /entries:
    get:
      description: Get all hydration entries for the user / Получить все записи пользователя
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/hydration.HydrationEntry'
            type: array
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get all hydration entries / Получить все записи
      tags:
      - hydration
    post:
      consumes:
      - application/json
      description: Add a new hydration entry for the user / Добавить новую запись
        о приёме воды
      parameters:
      - description: Entry data / Данные записи
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/hydration.CreateEntryRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/hydration.HydrationEntry'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Add hydration entry / Добавить запись о приёме воды
      tags:
      - hydration
  /goal:
    put:
      consumes:
      - application/json
      description: Update daily hydration goal for the user / Обновить дневную цель
        пользователя
      parameters:
      - description: Goal data / Новая цель
        in: body
        name: data
        required: true
        schema:
          additionalProperties:
            type: integer
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Update daily goal / Обновить дневную цель
      tags:
      - hydration
  /stats:
    get:
      description: Get hydration statistics for the user / Получить статистику пользователя
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/hydration.HydrationStats'
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get hydration stats / Получить статистику
      tags:
      - hydration
swagger: "2.0"
